// src/components/modals/AccessibilityModal.svelte
<script lang="ts">
  import { Dialog } from 'bits-ui';
  import DialogContent from '$components/ui/DialogContent.svelte';
  import DialogHeader from '$components/ui/DialogHeader.svelte';
  import SettingRow from '$components/ui/SettingRow.svelte';
  import Switch from '$components/ui/Switch.svelte';
  import Slider from '$components/ui/Slider.svelte';
  import { Select } from 'bits-ui';
  import SelectTrigger from '$components/ui/SelectTrigger.svelte';
  import SelectContent from '$components/ui/SelectContent.svelte';
  import SelectItem from '$components/ui/SelectItem.svelte';
  import Button from '$components/ui/Button.svelte';
  import KeybindSettings from '$components/modals/KeybindSettings.svelte';
  import { ViewConfig, defaultKeyBindings } from '$lib/view/constants';
  import type { FontSize } from '$lib/stores/settings.svelte';
  import { settings } from '$lib/stores/settings.svelte';
  import { RotateCcw } from 'lucide-svelte';
  import { theme } from '$lib/stores/theme.svelte';

  interface Props {
    open: boolean;
    onOpenChange: (open: boolean) => void;
  }

  let { open, onOpenChange }: Props = $props();

  let isTabular = $derived(settings.current.viewMode === 'tabular');
</script>

<Dialog.Root {open} {onOpenChange}>
  <DialogContent id="accessibility-modal" class="sm:max-w-lg">
    <DialogHeader title="Settings" description="Customize your experience with display and accessibility options." />
    <div class="space-y-6 py-4 max-h-[65vh] modal-scroll">
      <!-- Display Section -->
      <section class="space-y-1">
        <div class="mb-3">
          <h3 class="text-sm font-semibold text-foreground">Display</h3>
          <p class="text-xs text-muted-foreground">Customize colors, contrast, and text size</p>
        </div>
        <div class="space-y-0.5">
          <SettingRow label="Color Theme" description="Light, dark, or match system" htmlFor="theme-select-modal" class="hover:bg-accent/50">{@render themeSelect()}</SettingRow>
          <SettingRow label="Font Size" description="Adjust text size across the app" htmlFor="font-size-select-modal" class="hover:bg-accent/50">{@render fontSizeSelect()}</SettingRow>
          <SettingRow label="High Contrast" description="Increase visual distinction" htmlFor="high-contrast-toggle-modal" class="hover:bg-accent/50">{@render highContrastToggle()}</SettingRow>
        </div>
      </section>

      <!-- Grid View Section -->
      <section class="space-y-1">
        <div class="mb-3">
          <h3 class="text-sm font-semibold text-foreground">Grid View</h3>
          <p class="text-xs text-muted-foreground">Configure how the power grid is displayed</p>
        </div>
        <div class="space-y-0.5">
          <SettingRow label="Display Mode" description="Interactive map or data tables" htmlFor="view-mode-select" class="hover:bg-accent/50">{@render viewModeSelect()}</SettingRow>
          <SettingRow label="Animations" description="Animated power flow on lines" htmlFor="animations-toggle-modal" disabled={isTabular} class="hover:bg-accent/50">{@render animationsToggle()}</SettingRow>
          <SettingRow label="Map Labels" description="Show substation names on map" htmlFor="map-labels-toggle-modal" disabled={isTabular} class="hover:bg-accent/50">{@render mapLabelsToggle()}</SettingRow>
          <SettingRow label="Zoom Speed" description="Mouse wheel sensitivity" htmlFor="zoom-sensitivity-slider" disabled={isTabular} class="hover:bg-accent/50">{@render zoomSlider()}</SettingRow>
        </div>
      </section>

      <!-- Keyboard Shortcuts Section -->
      <section class="space-y-4">
        <div class="flex items-center justify-between">
          <h3 class="text-sm font-semibold text-muted-foreground uppercase tracking-wide">Keyboard Shortcuts</h3>
          <Button
            variant="ghost"
            size="sm"
            onclick={() => settings.update({ keyBindings: defaultKeyBindings })}
            class="h-7 px-2 text-xs"
          >
            <RotateCcw class="h-3 w-3 mr-1.5" />
            Reset
          </Button>
        </div>
        <KeybindSettings
          bindings={settings.current.keyBindings}
          onBindingsChange={(bindings) => settings.update({ keyBindings: bindings })}
        />
      </section>
    </div>
  </DialogContent>
</Dialog.Root>

{#snippet themeSelect()}
  <Select.Root type="single" value={theme.current} onValueChange={(value) => { if (value) theme.current = value as any; }}>
    <SelectTrigger id="theme-select-modal" class="w-auto min-w-32">
      <span data-slot="select-value">{theme.current === 'light' ? 'Light' : theme.current === 'dark' ? 'Dark' : 'System'}</span>
    </SelectTrigger>
    <SelectContent>
      <SelectItem value="light">Light</SelectItem>
      <SelectItem value="dark">Dark</SelectItem>
      <SelectItem value="system">System</SelectItem>
    </SelectContent>
  </Select.Root>
{/snippet}

{#snippet fontSizeSelect()}
  <Select.Root type="single" value={settings.current.fontSize} onValueChange={(value) => { if (value) settings.update({ fontSize: value as FontSize }); }}>
    <SelectTrigger id="font-size-select-modal" class="w-auto min-w-32">
      <span data-slot="select-value">{settings.current.fontSize === 'sm' ? 'Small' : settings.current.fontSize === 'base' ? 'Default' : settings.current.fontSize === 'lg' ? 'Large' : 'Extra Large'}</span>
    </SelectTrigger>
    <SelectContent>
      <SelectItem value="sm">Small</SelectItem>
      <SelectItem value="base">Default</SelectItem>
      <SelectItem value="lg">Large</SelectItem>
      <SelectItem value="xl">Extra Large</SelectItem>
    </SelectContent>
  </Select.Root>
{/snippet}

{#snippet highContrastToggle()}
  <Switch
    id="high-contrast-toggle-modal"
    checked={settings.current.isHighContrast}
    onCheckedChange={(checked) => settings.update({ isHighContrast: checked })}
  />
{/snippet}

{#snippet viewModeSelect()}
  <Select.Root type="single" value={settings.current.viewMode} onValueChange={(value) => { if (value) settings.update({ viewMode: value as 'map' | 'tabular' }); }}>
    <SelectTrigger id="view-mode-select" class="w-auto min-w-32">
      <span data-slot="select-value">{settings.current.viewMode === 'map' ? 'Map' : 'Tabular'}</span>
    </SelectTrigger>
    <SelectContent>
      <SelectItem value="map">Map</SelectItem>
      <SelectItem value="tabular">Tabular</SelectItem>
    </SelectContent>
  </Select.Root>
{/snippet}

{#snippet animationsToggle()}
  <Switch
    id="animations-toggle-modal"
    checked={settings.current.animationsEnabled}
    onCheckedChange={(checked) => settings.update({ animationsEnabled: checked })}
    disabled={isTabular}
  />
{/snippet}

{#snippet mapLabelsToggle()}
  <Switch
    id="map-labels-toggle-modal"
    checked={settings.current.renderMapLabels}
    onCheckedChange={(checked) => settings.update({ renderMapLabels: checked })}
    disabled={isTabular}
  />
{/snippet}

{#snippet zoomSlider()}
  <div class="flex items-center gap-2 w-auto min-w-32">
    <Slider
      id="zoom-sensitivity-slider"
      min={ViewConfig.ZOOM_SENSITIVITY_MIN}
      max={ViewConfig.ZOOM_SENSITIVITY_MAX}
      step={ViewConfig.ZOOM_SENSITIVITY_STEP}
      value={settings.current.zoomSensitivity}
      onValueChange={(value) => settings.update({ zoomSensitivity: value })}
      disabled={isTabular}
      aria-label="Zoom speed"
      class="flex-1"
    />
    <span class="text-xs text-muted-foreground w-6 text-right tabular-nums font-mono">
      {settings.current.zoomSensitivity.toFixed(1)}
    </span>
  </div>
{/snippet}

// blackoutusa/components/modals/accessibility-modal.tsx
"use client";

import { useTheme } from "next-themes";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Switch } from "@/components/ui/switch";
import { Slider } from "@/components/ui/slider";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { KeybindSettings } from "@/components/settings/keybind-settings";
import { ViewConfig } from "@/lib/game/config";
import { KeyBindings, defaultKeyBindings } from "@/lib/game/key-bindings";

interface AccessibilityModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;

  // Game-specific settings
  viewMode?: 'visual' | 'tabular';
  onViewModeChange?: (mode: 'visual' | 'tabular') => void;
  animationsEnabled?: boolean;
  onAnimationsEnabledChange?: (enabled: boolean) => void;
  renderCanvasText?: boolean;
  onRenderCanvasTextChange?: (enabled: boolean) => void;
  keyBindings?: KeyBindings;
  onKeyBindingsChange?: (bindings: KeyBindings) => void;
  showDetailsInSidebar?: boolean;
  onShowDetailsInSidebarChange?: (enabled: boolean) => void;
  zoomSensitivity?: number;
  onZoomSensitivityChange?: (value: number) => void;
  fontSize?: 'sm' | 'base' | 'lg' | 'xl';
  onFontSizeChange?: (size: 'sm' | 'base' | 'lg' | 'xl') => void;
  isHighContrast?: boolean;
  onIsHighContrastChange?: (enabled: boolean) => void;
}

export function AccessibilityModal({
  open,
  onOpenChange,
  viewMode,
  onViewModeChange,
  animationsEnabled,
  onAnimationsEnabledChange,
  renderCanvasText,
  onRenderCanvasTextChange,
  keyBindings,
  onKeyBindingsChange,
  showDetailsInSidebar,
  onShowDetailsInSidebarChange,
  zoomSensitivity,
  onZoomSensitivityChange,
  fontSize,
  onFontSizeChange,
  isHighContrast,
  onIsHighContrastChange,
}: AccessibilityModalProps) {
  const { theme, setTheme } = useTheme();

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Accessibility Settings</DialogTitle>
          <DialogDescription>
            Adjust display settings for a better experience.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-6 py-4 max-h-[65vh] overflow-y-auto pr-4 -mr-4">
          {/* General Section */}
          <div className="space-y-4">
            <h3 className="text-lg font-medium border-b pb-2">General</h3>
            <div className="grid grid-cols-[1fr_auto] items-center gap-x-4">
              <Label htmlFor="theme-select-modal" className="text-base font-normal">
                Color Theme
              </Label>
              <Select value={theme} onValueChange={(value) => setTheme(value)}>
                <SelectTrigger id="theme-select-modal" className="w-[180px] justify-self-end">
                  <SelectValue placeholder="Select theme" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="light">Light</SelectItem>
                  <SelectItem value="dark">Dark</SelectItem>
                  <SelectItem value="system">System</SelectItem>
                </SelectContent>
              </Select>
            </div>
            {fontSize !== undefined && onFontSizeChange && (
              <div className="grid grid-cols-[1fr_auto] items-center gap-x-4">
                <Label htmlFor="font-size-select-modal" className="text-base font-normal">
                  Font Size
                </Label>
                <Select value={fontSize} onValueChange={(value: 'sm' | 'base' | 'lg' | 'xl') => onFontSizeChange(value)}>
                  <SelectTrigger id="font-size-select-modal" className="w-[180px] justify-self-end">
                    <SelectValue placeholder="Select size" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="sm">Small</SelectItem>
                    <SelectItem value="base">Default</SelectItem>
                    <SelectItem value="lg">Large</SelectItem>
                    <SelectItem value="xl">Extra Large</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}
              {isHighContrast !== undefined && onIsHighContrastChange && (
              <div className="grid grid-cols-[1fr_auto] items-center gap-x-4">
                <Label htmlFor="high-contrast-toggle-modal" className="text-base font-normal">
                  High Contrast Mode
                </Label>
                <Switch
                  id="high-contrast-toggle-modal"
                  checked={isHighContrast}
                  onCheckedChange={onIsHighContrastChange}
                  className="justify-self-end"
                />
              </div>
              )}
          </div>

          {/* Electric Grid Section */}
          <div className="space-y-4">
            <h3 className="text-lg font-medium border-b pb-2">Electric Grid</h3>
            {viewMode !== undefined && onViewModeChange && (
              <div className="grid grid-cols-[1fr_auto] items-center gap-x-4">
                <Label htmlFor="view-mode-select" className="text-base font-normal">
                  Display Mode
                </Label>
                <Select value={viewMode} onValueChange={(value: 'visual' | 'tabular') => onViewModeChange(value)}>
                  <SelectTrigger id="view-mode-select" className="w-[180px] justify-self-end">
                    <SelectValue placeholder="Select mode" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="visual">Visual</SelectItem>
                    <SelectItem value="tabular">Tabular</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}
            {animationsEnabled !== undefined && onAnimationsEnabledChange && (
              <div className="grid grid-cols-[1fr_auto] items-center gap-x-4">
                <Label htmlFor="animations-toggle-modal" className="text-base font-normal" aria-disabled={viewMode !== 'visual'}>
                  Enable Animations
                </Label>
                <Switch
                  id="animations-toggle-modal"
                  checked={animationsEnabled}
                  onCheckedChange={onAnimationsEnabledChange}
                  disabled={viewMode !== 'visual'}
                  className="justify-self-end"
                />
              </div>
            )}
            {renderCanvasText !== undefined && onRenderCanvasTextChange && (
              <div className="grid grid-cols-[1fr_auto] items-center gap-x-4">
                <Label htmlFor="canvas-text-toggle-modal" className="text-base font-normal" aria-disabled={viewMode !== 'visual'}>
                  Show Map Labels
                </Label>
                <Switch
                  id="canvas-text-toggle-modal"
                  checked={renderCanvasText}
                  onCheckedChange={onRenderCanvasTextChange}
                  disabled={viewMode !== 'visual'}
                  className="justify-self-end"
                />
              </div>
            )}
            {zoomSensitivity !== undefined && onZoomSensitivityChange && (
              <div className="grid grid-cols-[1fr_auto] items-center gap-x-4">
                <Label htmlFor="zoom-sensitivity-slider" className="text-base font-normal" aria-disabled={viewMode !== 'visual'}>
                  Zoom Sensitivity
                </Label>
                <div className="flex items-center gap-2 w-[180px] justify-self-end">
                  <Slider
                    id="zoom-sensitivity-slider"
                    min={ViewConfig.ZOOM_SENSITIVITY_MIN}
                    max={ViewConfig.ZOOM_SENSITIVITY_MAX}
                    step={ViewConfig.ZOOM_SENSITIVITY_STEP}
                    value={[zoomSensitivity]}
                    onValueChange={(value) => onZoomSensitivityChange(value[0])}
                    disabled={viewMode !== 'visual'}
                    aria-label="Zoom speed"
                  />
                </div>
              </div>
            )}
          </div>

          {/* Layout Section */}
          <div className="space-y-4">
            <h3 className="text-lg font-medium border-b pb-2">Layout</h3>
            {showDetailsInSidebar !== undefined && onShowDetailsInSidebarChange && (
              <div className="grid grid-cols-[1fr_auto] items-center gap-x-4">
                <Label htmlFor="sidebar-details-toggle-modal" className="text-base font-normal">
                  Show Substations in Sidebar
                </Label>
                <Switch
                  id="sidebar-details-toggle-modal"
                  checked={showDetailsInSidebar}
                  onCheckedChange={onShowDetailsInSidebarChange}
                  className="justify-self-end"
                />
              </div>
            )}
          </div>

          {/* Keyboard Shortcuts Section */}
          {keyBindings && onKeyBindingsChange && (
            <div className="border-t pt-6">
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-lg font-medium">Keyboard Shortcuts</h3>
                <Button variant="secondary" onClick={() => onKeyBindingsChange(defaultKeyBindings)}>Reset to Defaults</Button>
              </div>
              <KeybindSettings bindings={keyBindings} onBindingsChange={onKeyBindingsChange} />
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
