// src/components/modals/QuitModal.svelte
<script lang="ts">
  import { Dialog } from 'bits-ui';
  import DialogContent from '$components/ui/DialogContent.svelte';
  import DialogHeader from '$components/ui/DialogHeader.svelte';
  import DialogTitle from '$components/ui/DialogTitle.svelte';
  import DialogDescription from '$components/ui/DialogDescription.svelte';
  import Button from '$components/ui/Button.svelte';
  import { hcVariant } from '$lib/utils';
  import { RotateCw, ArrowRight, LogOut, Play } from 'lucide-svelte';

  interface Props {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    day: number;
    onQuitToStart: () => void;
    onReplayDay: (currentDay: number) => void;
    onNextDay: (currentDay: number) => void;
    isHighContrast?: boolean;
  }

  let { open, onOpenChange, day, onQuitToStart, onReplayDay, onNextDay, isHighContrast }: Props = $props();
</script>

<Dialog.Root {open} {onOpenChange}>
  <DialogContent id="quit-modal" class="sm:max-w-lg font-sans" overlayClass="bg-black/70">
    <DialogHeader>
      <DialogTitle class="text-2xl">Quit the game?</DialogTitle>
      <DialogDescription>Choose how to continue your session.</DialogDescription>
    </DialogHeader>
    <div role="group" aria-label="Quit actions" class="grid grid-cols-1 gap-2 pt-2">
      <Button
        class="w-full justify-center gap-2"
        onclick={() => onOpenChange(false)}
      >
        <Play class="h-4 w-4" aria-hidden="true" />
        <span>Back to work!</span>
      </Button>
      <div class="grid grid-cols-2 gap-2">
        <Button
          variant={hcVariant(isHighContrast ?? false)}
          class="w-full justify-center gap-2"
          onclick={() => onReplayDay(day)}
        >
          <RotateCw class="h-4 w-4" aria-hidden="true" />
          <span>Replay Day</span>
        </Button>
        <Button
          variant={hcVariant(isHighContrast ?? false)}
          class="w-full justify-center gap-2"
          onclick={() => onNextDay(day)}
        >
          <span>Next Day</span>
          <ArrowRight class="h-4 w-4" aria-hidden="true" />
        </Button>
      </div>
      <Button
        variant="destructive"
        size="sm"
        class="w-full justify-center gap-2"
        onclick={onQuitToStart}
      >
        <LogOut class="h-4 w-4" aria-hidden="true" />
        <span>Home Page</span>
      </Button>
    </div>
  </DialogContent>
</Dialog.Root>

// blackoutusa/components/modals/quit-modal.tsx
"use client";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { RotateCw, ArrowRight, LogOut } from "lucide-react"

interface QuitModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  day: number;
  onQuitToStart: () => void;
  onReplayDay: (currentDay: number) => void;
  onNextDay: (currentDay: number) => void;
}

export function QuitModal({ open, onOpenChange, day, onQuitToStart, onReplayDay, onNextDay }: QuitModalProps) {
  return ( <Dialog open={open} onOpenChange={onOpenChange}> <DialogContent className="sm:max-w-[600px] font-share-tech">
        <DialogHeader>
          <DialogTitle className="text-3xl font-bold">Quit the game?</DialogTitle>
          <DialogDescription className="sr-only">Quit options</DialogDescription>
        </DialogHeader>
        <div role="group" aria-label="Quit actions" className="flex flex-col gap-3 py-4 text-base">
          <Button variant="destructive" className="w-full justify-center gap-2 py-4 text-base" onClick={onQuitToStart}>
            <LogOut className="h-5 w-5" aria-hidden="true" />
            <span>Quit to Start</span>
          </Button>
          <Button variant="secondary" className="w-full justify-center gap-2 py-4 text-base" onClick={() => onReplayDay(day)}>
            <RotateCw className="h-5 w-5" aria-hidden="true" />
            <span>Restart This Day</span>
          </Button>
          <Button className="w-full justify-center gap-2 py-4 text-base" onClick={() => onNextDay(day)}>
            <span>Skip to Next Day</span>
            <ArrowRight className="h-5 w-5" aria-hidden="true" />
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
